recipes/getrecipeapp/urls.py
from django.urls import path, include
from getrecipeapp import views
from django.contrib.auth.views import LogoutView
from rest_framework import routers
from getrecipeapp.api_views import CategoryViewSet, TagViewSet, ComplexityViewSet, DishesActiveViewSet, UserViewSet

router = routers.DefaultRouter()
router.register('category', CategoryViewSet)
router.register('tag', TagViewSet)
router.register('complexity', ComplexityViewSet)
router.register('dish_active', DishesActiveViewSet)
router.register('users', UserViewSet)

app_name = 'getrecipeapp'

urlpatterns = [
    path('', views.DishesView.as_view(), name='index'),
    path('category/<str:tag>', views.DishesViewCategory.as_view(), name='index-category'),
    path('search/', views.DishesViewSearch.as_view(), name='search'),
    path('about/', views.About.as_view(), name='about'),
    path('post/<int:pk>', views.DishesDetailView.as_view(), name='post'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('create-dishes/', views.DishesCreate.as_view(), name='create-dishes'),
    path('update-dishes/<int:pk>', views.DishesUpdate.as_view(), name='update-dishes'),
    path('delete-dishes/<int:pk>', views.DishesDelete.as_view(), name='delete-dishes'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('access_denied/', views.AccessDenied.as_view(), name='access_denied'),
    path('profile/<int:pk>', views.DetailUser.as_view(), name='user-profile'),
    path('generate-token/', views.generate_token, name='generate_token'),
    path('api/v0/', include(router.urls)),
]

recipes/recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('getrecipeapp.urls', namespace='dishes')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

recipes/getrecipeapp/models.py
from django.db import models
from django.core.files.images import get_image_dimensions
from PIL import Image
from django.core.exceptions import ValidationError


# Create your models here.
class ActiveManager(models.Manager):

    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)


class NameModelMixin(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True


class Category(NameModelMixin):

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Tag(NameModelMixin):

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class Complexity(NameModelMixin):

    class Meta:
        verbose_name = 'Уровень сложности приготовления'
        verbose_name_plural = 'Уровни сложности приготовления'


def validate_image(image_obj):
    file_size = image_obj.file.size
    megabyte_limit = 1.0
    if file_size > megabyte_limit*1024*1024:
        raise ValidationError('Размер вашей картинки %s мб. Максимальный размер картинки %s мб' %
                              (round(file_size/1024/1024, 2), megabyte_limit))


class Dishes(IsActiveMixin):
    title = models.CharField(max_length=64, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='tags')
    complexity = models.ForeignKey(Complexity, on_delete=models.CASCADE)
    timeprocess = models.CharField(max_length=16, blank=True)
    calories = models.CharField(max_length=6, blank=True)
    rating = models.CharField(max_length=3, blank=True)
    image = models.ImageField(upload_to='images_small', null=True, blank=True,
                              validators=[validate_image],
                              help_text='Максимальный размер картинки 1 мб, резрешение 150х150')
    description = models.TextField()
    image_full = models.ImageField(upload_to='images_full', null=True, blank=True,
                                   validators=[validate_image],
                                   help_text='Максимальный размер картинки 1 мб')
    description_full = models.TextField(blank=True)
    nutrition = models.TextField(blank=True)
    ingredients_clr = models.TextField(blank=True)
    instructions = models.TextField(blank=True)
    link = models.TextField(blank=True)

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

    @staticmethod
    def resize_image(set_h, set_w, image):
        h, w = get_image_dimensions(image.path)
        img = Image.open(image)
        if h > set_h or w > set_w:
            output_size = (set_h, set_w)
            img.thumbnail(output_size)
            img.save(image.path)

    def save(self, *args, **kwargs):
        super(Dishes, self).save(*args, **kwargs)
        if self.image:
            self.resize_image(150, 150, self.image)
        if self.image_full:
            self.resize_image(375, 500, self.image_full)

    def display_tags(self):
        tags = self.tags.all()
        return ', '.join([tag.name for tag in tags])

recipes/getrecipeapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ContactForm(forms.Form):
    name = forms.CharField(label='Введите ваше имя',
                           widget=forms.TextInput(attrs={'placeholder': 'Имя',
                                                         'class': 'form-control'}))
    email = forms.EmailField(label='Введите вашу почту',
                             widget=forms.TextInput(attrs={'placeholder': 'test@email.com',
                                                           'class': 'form-control'})
                             )
    message = forms.CharField(label='Сообщение',
                              widget=forms.TextInput(attrs={'placeholder': 'сообщение',
                                                            'class': 'form-control'})
                              )


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

recipes/getrecipeapp/views.py
from django.shortcuts import redirect, get_list_or_404, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from .models import Dishes, Tag
from .forms import ContactForm, RegistrationForm
from django.core.mail import send_mail
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView, TemplateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token


class DishesView(ListView):
    model = Dishes
    paginate_by = 6
    template_name = 'getrecipeapp/index.html'
    context_object_name = 'dishes'
    ordering = '-id'
    queryset = Dishes.active_objects. \
        select_related('complexity'). \
        prefetch_related('tags').all()
    extra_context = {'title': 'Главная страница'}


class DishesViewCategory(ListView):
    model = Dishes
    paginate_by = 6
    template_name = 'getrecipeapp/index_for_category.html'
    ordering = '-id'
    context_object_name = 'dishes'
    extra_context = {'title': 'Категории'}

    def get_queryset(self):
        tag = self.kwargs['tag']
        result = Dishes.active_objects. \
            select_related('complexity'). \
            prefetch_related('tags').filter(tags__name__icontains=tag)
        return result


class DishesViewSearch(ListView):
    model = Dishes
    paginate_by = 6
    template_name = 'getrecipeapp/search.html'
    ordering = '-id'
    context_object_name = 'dishes'
    extra_context = {'title': 'Поиск'}

    def get_queryset(self):
        result = Dishes.active_objects.all()
        q = self.request.GET['q']
        if q:
            result = Dishes.active_objects.select_related('complexity'). \
                prefetch_related('tags').filter(Q(title__icontains=q) |
                                                Q(tags__name__icontains=q) |
                                                Q(description__icontains=q) |
                                                Q(description_full__icontains=q))
        return result


class About(TemplateView):
    template_name = 'getrecipeapp/about.html'
    extra_context = {'title': 'О нас'}


class DishesDetailView(DetailView):
    model = Dishes
    template_name = 'getrecipeapp/post.html'
    extra_context = {'title': 'Рецепт: '}


class Contact(FormView):
    form_class = ContactForm
    template_name = 'getrecipeapp/contact.html'
    success_url = reverse_lazy('dishes:index')
    extra_context = {'title': 'Форма обратной связи'}

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']

        send_mail(f'Contact message from {name}',
                  f'Here is the {message}.',
                  'from@example.com',
                  [email],
                  fail_silently=True,
                  )

        return super().form_valid(form)


class DishesCreate(LoginRequiredMixin, CreateView):
    model = Dishes
    fields = '__all__'
    success_url = reverse_lazy('dishes:index')
    template_name = 'getrecipeapp/create-dishes.html'
    extra_context = {'title': 'Добавить\Обновить рецепт'}


class DishesUpdate(LoginRequiredMixin, UpdateView):
    model = Dishes
    fields = '__all__'
    template_name = 'getrecipeapp/create-dishes.html'
    extra_context = {'title': 'Добавить\Обновить рецепт'}

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("dishes:post", kwargs={"pk": pk})


class DishesDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Dishes
    success_url = reverse_lazy('dishes:index')
    template_name = 'getrecipeapp/delete_dishes_confirm.html'
    extra_context = {'title': 'Удалить рецепт'}

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return redirect('dishes:access_denied')


class UserLoginView(LoginView):
    template_name = 'getrecipeapp/login.html'
    extra_context = {'title': 'Логин'}


class UserRegistrationView(CreateView):
    template_name = 'getrecipeapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('dishes:login')
    extra_context = {'title': 'Регистрация'}


class AccessDenied(TemplateView):
    template_name = 'getrecipeapp/accesdenied.html'
    extra_context = {'title': 'Доступ запрещен'}


class DetailUser(DetailView):
    model = User
    template_name = 'getrecipeapp/user.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_queryset(self):
        user = self.request.user
        return User.objects.filter(id=user.id)


def generate_token(request):
    user = request.user
    try:
        if user.auth_token:
            user.auth_token.delete()
            Token.objects.create(user=user)
        else:
            Token.objects.create(user=user)
    except Token.DoesNotExist:
        Token.objects.create(user=user)
    return HttpResponseRedirect(reverse_lazy('dishes:user-profile', kwargs={'pk': user.pk}))

recipes/getrecipeapp/templates/getrecipeapp/about.html
{% extends 'base_templates.html' %}
        <!-- Main Content-->
{% block context %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/accesdenied.html
{% extends 'base_templates.html' %}
{% block context %}
<div class="alert alert-danger" role="alert">
  Ошибка доступа!!! Вы не можете удалить статью, т.к это могут делать только администраторы портала
</div>
<p><a href="{% url 'dishes:index' %}"><button>Назад</button></a></p>
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/contact.html
{% extends 'base_templates.html' %}
{% block context %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">
                    <form method="post" id="form">
                        {% csrf_token %}
                        {{ form.as_table }}</br>
                        <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
 {% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/create-dishes.html
{% extends 'base_templates.html' %}
{% load cache %}
{% block context %}
{% cache 500 form_create_dishes %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-12 col-lg-8 col-xl-7">
                <div class="my-5">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endcache %}
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/delete_dishes_confirm.html
{% extends 'base_templates.html' %}
{% block context %}
    <article class="mb-4 col-md-10">
        <div class="container px-4 px-lg-5 col-md-10" >
            <div class="col-md-10">

                <h2 class="section-heading">{{ object.title }}</h2>
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <p><img src=" {{ object.image_full.url }} " /></p>
                        <p>{{ object.description}}</p>
                    </div>
                </br>
                <p style="text-align: center; color: red">Статья будет удалена, Вы уверены?</p>

            </div>
            </br>
          <form method="post">
            {% csrf_token %}
              <div class="d-grid gap-2">
                  <button class="btn btn-success text-uppercase" type="submit">Да</button>
              </div>
          </form>
        </div>
    </article>
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/get_count_dishes_template.html
<p class="post-meta" style="font-size:11pt">Найдено всего рецептов: {{ page_obj.paginator.count }}</p>

recipes/getrecipeapp/templates/getrecipeapp/index.html
{% extends 'base_templates.html' %}
{% block title %} Главная страница {% endblock %}
{% block style %}
    <style>
       .leftimg {
        float:left; /* Выравнивание по левому краю */
        margin: 34px 17px 7px 0; /* Отступы вокруг картинки */
       }
      </style>
{% endblock %}
{% block context %}
    <div class="col-md-10">
        <!-- Post preview-->
<!--        <p class="post-meta" style="font-size:11pt">-->
<!--                Все теги: {{ tag_list.all|join:', ' }}-->
<!--            </p>-->
        {% for item in dishes %}
        <div class="post-preview">
            <a href="{% url 'dishes:post' pk=item.id %}">
                <h2 class="post-title">{{ item.title }}</h2></a>
                <img src="{{ item.image.url }}" class="leftimg"/>
                <p class="post-subtitle">{{ item.description }}</p>

            <p class="post-meta">
                Время: {{ item.timeprocess }}
                {% if item.complexity %}Сложность: {{ item.complexity }}{% endif %}
                Калорийность: {{ item.calories }}
            </p>
            <p class="post-meta">
                Категории: {{ item.tags.all|join:', '}}
            </p>
            {% if user.is_authenticated %}
            <p class="post-meta article" style="text-align: right">Статью:
                <a href="{% url 'dishes:update-dishes' pk=item.id%}">Изменить</a>
                 / <a href="{% url 'dishes:delete-dishes' pk=item.id%}">Удалить</a>
            </p>
            {% endif %}
        </div>
        {% endfor %}
        <!-- Divider-->
        <hr class="my-4" />
            <span class="current" style="display: block; text-align: center;">
                Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
        </div></br>
        <div class="pagination col-md-10" style="display: block; text-align: center;">
            <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-primary text-uppercase" href="?page=1">Первая</a>
                <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.previous_page_number }}">&laquo; Предыдущая</a>
            {% endif %}


            {% if page_obj.has_next %}
                <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.next_page_number }}">Следующая &raquo;</a>
                <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/index_for_category.html
{% extends 'base_templates.html' %}
{% block style %}
    <style>
       .leftimg {
        float:left; /* Выравнивание по левому краю */
        margin: 34px 17px 7px 0; /* Отступы вокруг картинки */
       }
      </style>
{% endblock %}
{% block context %}
    {% include "getrecipeapp/search_template.html" %}
    <div class="col-md-10">
        {% include "getrecipeapp/tags_template.html" %}
        {% include "getrecipeapp/get_count_dishes_template.html" %}
        {% include "getrecipeapp/view_dishes_template.html" %}
        <!-- Divider-->
        <hr class="my-4" />
            <span class="current" style="display: block; text-align: center;">
                Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
        </div></br>
{% include "getrecipeapp/paginate_template.html" %}
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/login.html
{% extends 'base_templates.html' %}
{% block context %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}</br>
                        <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
 {% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/paginate_template.html
<div class="pagination col-md-10" style="display: block; text-align: center;">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn btn-primary text-uppercase" href="?page=1">Первая</a>
            <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.previous_page_number }}">&laquo; Предыдущая</a>
        {% endif %}

        {% if page_obj.has_next %}
            <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.next_page_number }}">Следующая &raquo;</a>
            <a class="btn btn-primary text-uppercase" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        {% endif %}
    </span>
</div>

recipes/getrecipeapp/templates/getrecipeapp/post.html
{% extends 'base_templates.html' %}
{% block title %} {{ title }}{{ object.title }} {% endblock %}
{% block context %}
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10">
                    <h2 class="section-heading">{{ object.title }}</h2>{{test}}
                    <div class="post-meta" style="text-align: right">
                        <a href="{% url 'dishes:update-dishes' pk=object.id%}">Изменить</a> /
                        <a href="{% url 'dishes:delete-dishes' pk=object.id%}">Удалить</a>
                    </div>
                    <p><img src=" {{ object.image_full.url }} " /></p>
                    <p>{{ object.description_full}}</p>
                    <hr>
                    {% autoescape off %}
                    <p>{{ object.nutrition }}</p>
                    <hr>
                    <p>{{ object.ingredients_clr }}</p>
                    <hr>
                    <h3>Приготовление блюда по рецепту:</h3>
                    <p>{{ object.instructions }}</p>
                    {% endautoescape %}
                </div>
            </div>
        </div>
    </article>
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/register.html
{% extends 'base_templates.html' %}
{% block context %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="my-5">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}</br>
                        <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
 {% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/search.html
{% extends 'base_templates.html' %}
{% block style %}
    <style>
       .leftimg {
        float:left; /* Выравнивание по левому краю */
        margin: 34px 17px 7px 0; /* Отступы вокруг картинки */
       }
      </style>
{% endblock %}
{% block context %}
{% include "getrecipeapp/get_count_dishes_template.html" %}
    <div class="col-md-10">
    {% include "getrecipeapp/view_dishes_template.html" %}
    <!-- Divider-->
    <hr class="my-4" />
        <span class="current" style="display: block; text-align: center;">
            Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
        </span>
    </div></br>
{% include "getrecipeapp/paginate_template.html" %}
{% endblock %}

recipes/getrecipeapp/templates/getrecipeapp/user.html
{% extends 'base_templates.html' %}
{% block context %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
          Пользователь: &nbsp; {{ user }} </br>
          Token: &nbsp; {{ user.auth_token }}
        </div>
        <hr>
        <form action="{% url 'dishes:generate_token' %}" method="post" class="row">
            {% csrf_token %}
            <button type="submit">Generate token</button>
        </form>
    </div>
</main>
{% endblock %}