recipes/getrecipeapp/urls.py
from django.urls import path, include
from getrecipeapp import views
from django.contrib.auth.views import LogoutView
from rest_framework import routers
from getrecipeapp.api_views import CategoryViewSet, TagViewSet, ComplexityViewSet, DishesActiveViewSet, UserViewSet

router = routers.DefaultRouter()
router.register('category', CategoryViewSet)
router.register('tag', TagViewSet)
router.register('complexity', ComplexityViewSet)
router.register('dish_active', DishesActiveViewSet)
router.register('users', UserViewSet)

app_name = 'getrecipeapp'

urlpatterns = [
    path('', views.DishesView.as_view(), name='index'),
    path('category/<str:tag>', views.DishesViewCategory.as_view(), name='index-category'),
    path('search/', views.DishesViewSearch.as_view(), name='search'),
    path('about/', views.About.as_view(), name='about'),
    path('post/<int:pk>', views.DishesDetailView.as_view(), name='post'),
    path('contact/', views.Contact.as_view(), name='contact'),
    path('create-dishes/', views.DishesCreate.as_view(), name='create-dishes'),
    path('update-dishes/<int:pk>', views.DishesUpdate.as_view(), name='update-dishes'),
    path('delete-dishes/<int:pk>', views.DishesDelete.as_view(), name='delete-dishes'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('access_denied/', views.AccessDenied.as_view(), name='access_denied'),
    path('profile/<int:pk>', views.DetailUser.as_view(), name='user-profile'),
    path('generate-token/', views.generate_token, name='generate_token'),
    path('api/v0/', include(router.urls)),
]

recipes/recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('getrecipeapp.urls', namespace='dishes')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

recipes/templates/base_templates.html
{% load static %}
{% load external_filters %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %}{{ title }}{% endblock %}</title>

        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block style %}{% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <h1><a class="navbar-brand" href="{% url 'dishes:index' %}">VT</a></h1>
                {% if user.is_authenticated %}
                <a href="{% url 'dishes:user-profile' pk=user.pk %}"><span style="text-align: right; color:white">{{ user|status_user }}</span></a>
                {% endif %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">

                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'dishes:index' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'dishes:about' %}">О нас</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%  url 'dishes:contact' %}">Контакты</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'dishes:create-dishes' %}">Добавить блюдо</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%  url 'dishes:logout' %}">Выход</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%  url 'dishes:login' %}">Вход</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%  url 'dishes:register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'assets/img/bigtastyfood.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Very Tasty</h1>
                            <h4>Блог о том, как готовить вкусно и полезно</h4>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
              {% block context %} {% endblock %}
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="{% static 'js/feedback.js' %}"></script>
    </body>
</html>